### ISSUE TITLE
Accesing index.js with webpack

### ISSUE THREAD

**Issue by rosskhanas** [zackargyle/react-bind-decorator#2]
I cannot use this module with webpack, probably adding `"main": "src/react-bind-decorator.js"` to `project.json` would fix the problem. I see there is `jsnext:main` property for rollup.

**Comment by zackargyle** [comment]
Totally missed that one. Seems like an easy enough change, mind making a PR and contributing? :)

**Comment by rosskhanas** [comment]
Sure, not, but seems like someone already made it :)

**Comment by zackargyle** [comment]
Oh man. Thanks anyway! He was so quick!
