### ISSUE TITLE
Can we add types for TypeScript support?

### ISSUE THREAD

**Issue by code-hunger** [zackargyle/react-bind-decorator#5]
This should be a very easy task. There's only a single function to be typed:

```
export default function bind() {
    return function(target) {
        Object.getOwnPropertyNames(target.prototype)
              .forEach(bindMethod(target))
        return target;
    };
}
```

And since the function it returns has the same type on input and output, it's type definition will be as simple as that:

`bind: <T>() => (target: T) => T;`

I'm not sure how to add it to this repo though. I was thinking it could be also uploaded to DefinitelyTyped, but I think it will be cleaner if it gets added right into this repo.

**Comment by zackargyle** [comment]
Hey! I'm not a big typescript user but happy to review a PR if you can figure it out! Would love to have the typings included for it.
